#!/bin/bash

NETWORK_INTERFACE=$1

#---PULL SNORT3---#
echo "`date`Pulling snort3 docker image from DockerHub"
docker pull lmanases/snort3:latest

#---PULL SNORT3 GRAFANA API---#
echo "`date` Pulling snort3 api docker iamge from DockerHub"
docker pull lmanases/api:latest

#---PULL SNORT3 GRAFANA---#
echo "`date` Pulling snort3 grafana docker image from DockerHub"
docker pull lmanases/snort3_grafana:latest

#---RUN THE SNORT3 CONTAINER WHICH STARTS SNORT3 APP---#
CURR_DIR=$(pwd)
SNORT3_LOGS=$CURR_DIR/Snort3/log/

docker run --name snort3 --network=host -d -v $SNORT3_LOGS:/var/log/snort/ lmanases/snort3:latest -i $NETWORK_INTERFACE

#---RUN THE API CONTAINER NEEDED TO PROCESS THE EVENTS GENERATED BY SNORT3 TO PASS THEM TO GRAGANA---#
docker run --name snort3_api  -p 5000:5000 --network=host -d -v $SNORT3_LOGS:/var/logs/ lmanases/api:latest

#---RUN THE GRAFANA CONTAINER TO BE ABLE TO CHECK THE DASHBOARDS ON THE UI---#
GRAFANA_PROV=$CURR_DIR/Grafana/provisioning/

docker run --name snort3_grafana -p 3000:3000 -d -e "GF_INSTALL_PLUGINS=marcusolsson-json-datasource"  -v $GRAFANA_PROV:/etc/grafana/provisioning lmanases/snort3_grafana:latest
